### PR TITLE
Create TemperatureConverter.py

### PR DESCRIPTION
**Pull request by ghost**
temperature converter between Farenheight, Celsius, and Kelvin
EDIT: BAD

### CODE REVIEW

**Comment by prepsure** [comment]
could you change the temperature script to work inside one function?

**Comment by JarnaChao09** [comment]
why ask for 1,2,and 3 to say C,F, or K, why not just use them as strings and check the first letter of the string to see if its C, F, or K

**Comment by prepsure** [comment]
not merging either of these until the code actually looks usable and makes sense for the user

**Comment by prepsure** [comment]
going to close this

**Pull request closed without merging**
